<a href="https://colab.research.google.com/github/DATA3320/Weekly/blob/main/Workbooks/Lecture06_workbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lecture 6 Student Workbook: Numpy

###  Problem 1.

Import numpy under the alias `np`.

In [ ]:
# Your answer here.

### Problem 2.

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 3.141s.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [ ]:
# Your answer here.

### Problem 3.

Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [ ]:
# Your answer here.

### Problem 4.

Mixing types (Strings, Numbers, Booleans).  Make an array of multiple types:

In [ ]:
# Your answer here.


### Problem 5.

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [ ]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)

```python
20
```

In [ ]:
# Your answer here.

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [ ]:
# Your answer here.

```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
# Your answer here.

```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [ ]:
# Your answer here.

```python
array([[ 8,  9],
       [13, 14]])
```

In [ ]:
# Your answer here.

### Problem 6.

Calculate the sum of all the numbers in `a`.

In [ ]:
# Your answer here.

### Problem 7.

Calculate the sum of each row in `a`.

In [ ]:
# Your answer here.

### Problem 8.

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [ ]:
# Your answer here.

### Problem 9.

Find the location of the minimum value in the following array `b`:

In [ ]:
np.random.seed(123)
b = np.random.randn(10)
b

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025,
        1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [ ]:
# Your answer here.

### Problem 10.

You have a dataset containing the test scores of 50 students in 5 subjects - Math, Physics, Chemistry, English, and Biology. Each student's scores are stored in a NumPy array of shape (5,). Write a program to perform the following tasks:

- 1. Create a 2-dimensional NumPy array of shape (50, 5) containing the scores of all the students.
- 2. Calculate the average scores of each student and store them in a 1-dimensional NumPy array of shape (50,).
- 3. Calculate the average score of each subject and store them in a 1-dimensional NumPy array of shape (5,).
- 4. Find the student who has the highest average score.
- 5. Print the average score of each subject and the highest average score of a student.

In [ ]:
# Your answer here.